services:
  front:
    build: ./front
    ports:
      - '3000:3000'
    depends_on:
      - back

  back:
    build: ./back
    ports:
      - '8080:8080'
    depends_on:
      postgresql-db:
          condition: service_healthy

  postgresql-db:
    image: postgres:latest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '80:80'

volumes:
  postgres_data:
