security:
  jwt:
    secret-sey: verysecretkeydonttellanybodyimserious

spring:
  application:
    name: NewsFlow

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d0ib7dvfte5s73fp66b0-a:5432/news_5nd6
    username: news_5nd6_user
    password: iMPXjZ9rl7wToE0luOkVT9CSETgvIUxI

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
  
  servlet:
    multipart.max-file-size: 10000MB
    multipart.max-request-size: 10000MB

cloud:
  firebase:
    storage-bucket: start-8fcf1.appspot.com
    service-access-key-path: /etc/secrets/firebase.json
